actor_bc_coef: 0.01
actor_learning_rate: 0.001
actor_ln: false
actor_n_hiddens: 3
batch_size: 1024
critic_bc_coef: 0.01
critic_learning_rate: 0.001
critic_ln: true
critic_n_hiddens: 3
dataset_name: walker2d-medium-expert-v2
eval_episodes: 10
eval_every: 5
eval_seed: 42
gamma: 0.99
group: gru_brac-walker2d-medium-expert-v2
hidden_dim: 256
name: gru_brac
noise_clip: 0.5
normalize_q: true
normalize_reward: false
normalize_states: false
num_epochs: 100
num_updates_on_epoch: 100
policy_freq: 2
policy_noise: 0.2
project: gru_brac
tau: 0.005
train_seed: 0
time_steps: 5
offline_data_cycle: 0
check_dataset: false
